version: "2"

run:
  timeout: 5m

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/"
      linters:
        - dupl
        - lll
    - path: "test/"
      linters:
        - lll
        - revive
        - staticcheck
    # Exclude kubebuilder annotations from comment-spacings rule
    - source: "^//\\+kubebuilder:"
      linters:
        - revive
linters:
  enable:
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1004"
        - "-QF1008"
        - "-ST1000"
        - "-ST1001"
        - "-ST1003"

formatters:
  enable:
    - gofmt
    - goimports
